### ISSUE TITLE
Able Player in iframe with different Domain Blocked by Browser on play.

### ISSUE THREAD

**Issue by mshubat** [ableplayer/ableplayer#518]
When Able Player is embedded in a an iframe on the page, with a different domain the play function is blocked by the browser.

```
ERROR Error: Uncaught (in promise): NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
    at player.js:2:9063
    at Array.forEach (<anonymous>)
    at M (player.js:2:9037)
    at a._onMessage (player.js:2:10765)
    at l.invokeTask (polyfills.1b391f26029e71638c65.js:1:7242)
    at Object.onInvokeTask (main.3a57a8d0f7bd11e68727.js:1:196458)
    at l.invokeTask (polyfills.1b391f26029e71638c65.js:1:7163)
    at a.runTask (polyfills.1b391f26029e71638c65.js:1:2651)
```

It appears that because the player is using 3rd party controls on top of the native player frame, the browser does not recognize the click as a user interaction with the youtube/vimeo from for example.

This basic html template should be enough to reproduce the issue.

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Embedded Test Page</title>
    </head>
    <body>
        <h2>Local - Embedded OCA Rewrite</h2>
        <!-- allow="autoplay" -->
	<iframe id="XRD" width="100%" height="1000px" src="https://ableplayer.github.io/ableplayer/demos/vimeo1.html"></iframe>
    </body>
</html>
```

There is a workaround for this issue by adding the `allow="autoplay"` attribute to the iframe. This however this is not always a viable solution as you do not always have control over the parent frame. For example our teams application is currently run in an iframe by other companies, so when they our application (which itself uses Able Player) the play function will be blocked as we are embedded from another domain in their page.

**Comment by mshubat** [comment]
I have tried to reproduce this issue in mobile Safari and Firefox and cannot. However, I can produce it in Chrome & Edge, leading me to believe this affects chromium based browsers in general. 

It appears to be a result of chromes initiative to stop autoplaying audio started several years ago. I would argue it is a bug in the implementation of this.
https://www.blog.google/products/chrome/improving-autoplay-chrome/

The current approach I am experimenting with is hiding player controls on initial load of the app, so the user click or interaction occurs on the iframe. Once the focus on the iframe is detected, the play event should fire safely without being blocked.

The player controls will then be added. I will make all this a completely optional. If the user does not provide the required attribute to the player everything should behave as usual.

Option could be something like `initially-expose-native-iframe`
